# Generated by Django 4.2.7 on 2023-11-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('time_fetched', models.DateTimeField()),
                ('fetch_status', models.IntegerField(blank=True, max_length=10, null=True)),
                ('raw_content', models.TextField(blank=True, null=True)),
                ('extracted_content', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('url', 'time_fetched')},
            },
        ),
    ]
